# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
# Frédéric <frosmont@free.fr>, 2014
# Maxime COQUEREL <max.coquerel@gmail.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: nova\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-04-06 06:16+0000\n"
"PO-Revision-Date: 2015-04-03 18:00+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: French (http://www.transifex.com/projects/p/nova/language/"
"fr/)\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: nova/filters.py:80
#, python-format
msgid "Filter %s returned 0 hosts"
msgstr "Filtre %s retourne 0 machines"

#: nova/service.py:161
#, python-format
msgid "Starting %(topic)s node (version %(version)s)"
msgstr "Démarrage du noeud %(topic)s (version %(version)s)"

#: nova/wsgi.py:149
#, python-format
msgid "%(name)s listening on %(host)s:%(port)s"
msgstr "%(name)s en écoute sur %(host)s : %(port)s"

#: nova/wsgi.py:253
msgid "Stopping WSGI server."
msgstr "Arrêt du serveur WSGI."

#: nova/wsgi.py:273
msgid "WSGI server has stopped."
msgstr "Le serveur WSGI a été arrêté."

#: nova/api/ec2/__init__.py:465
#, python-format
msgid ""
"Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr ""
"Requête non authorisé pour le controlleur=%(controller)s et l'action="
"%(action)s"

#: nova/api/ec2/cloud.py:415
#, python-format
msgid "Create snapshot of volume %s"
msgstr "Création de l'instantané du volume %s"

#: nova/api/ec2/cloud.py:458
#, python-format
msgid "Create key pair %s"
msgstr "Création du bi-clef %s"

#: nova/api/ec2/cloud.py:470
#, python-format
msgid "Import key %s"
msgstr "Importation de la clé %s"

#: nova/api/ec2/cloud.py:483
#, python-format
msgid "Delete key pair %s"
msgstr "Suppression du bi-clef %s"

#: nova/api/ec2/cloud.py:786
#, python-format
msgid "Get console output for instance %s"
msgstr "Récupération de la sortie de la console de l'instance %s"

#: nova/api/ec2/cloud.py:859
#, python-format
msgid "Create volume from snapshot %s"
msgstr "Création du volume à partir de l'instantané %s"

#: nova/api/ec2/cloud.py:863 nova/api/openstack/compute/contrib/volumes.py:163
#, python-format
msgid "Create volume of %s GB"
msgstr "Création d'un volume de %s Go"

#: nova/api/ec2/cloud.py:903
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr ""
"Montage du volume %(volume_id)s sur l'instance %(instance_id)s en tant que "
"%(device)s"

#: nova/api/ec2/cloud.py:933 nova/api/openstack/compute/contrib/volumes.py:392
#, python-format
msgid "Detach volume %s"
msgstr "Dé-montage du volume %s"

#: nova/api/ec2/cloud.py:1300
msgid "Allocate address"
msgstr "Allocation d'adresse"

#: nova/api/ec2/cloud.py:1305
#, python-format
msgid "Release address %s"
msgstr "Désallocation de l'adresse %s"

#: nova/api/ec2/cloud.py:1310
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr "Association de l'adresse %(public_ip)s avec l'instance %(instance_id)s"

#: nova/api/ec2/cloud.py:1343
#, python-format
msgid "Disassociate address %s"
msgstr "Désassociation de l'adresse %s"

#: nova/api/ec2/cloud.py:1496
#, python-format
msgid "Reboot instance %r"
msgstr "Re-démarrage de l'instance %r"

#: nova/api/ec2/cloud.py:1611
#, python-format
msgid "De-registering image %s"
msgstr "Dé-enregitrement de l'image %s"

#: nova/api/ec2/cloud.py:1647
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr "Image %(image_location)s enregistré avec l'id %(image_id)s"

#: nova/api/ec2/cloud.py:1716
#, python-format
msgid "Updating image %s publicity"
msgstr "Mis à jour de la publication de l'image %s"

#: nova/api/ec2/ec2utils.py:292
msgid "Timestamp is invalid."
msgstr "L'horodatage n'est pas valide."

#: nova/api/openstack/__init__.py:102
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr "%(url)s retourné avec HTTP %(status)d"

#: nova/api/openstack/__init__.py:291
msgid "V3 API has been disabled by configuration"
msgstr "L'API V3 a été désactivée par configuration "

#: nova/api/openstack/__init__.py:336
#, python-format
msgid "Loaded extensions: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:522
#, python-format
msgid "Fault thrown: %s"
msgstr "Erreur générée : %s"

#: nova/api/openstack/wsgi.py:525
#, python-format
msgid "HTTP exception thrown: %s"
msgstr "Exception HTTP générée : %s"

#: nova/api/openstack/compute/contrib/assisted_volume_snapshots.py:53
#: nova/api/openstack/compute/plugins/v3/assisted_volume_snapshots.py:56
#, python-format
msgid "Create assisted snapshot from volume %s"
msgstr "Créer un instantané assisté du volume %s"

#: nova/api/openstack/compute/contrib/assisted_volume_snapshots.py:64
#: nova/api/openstack/compute/contrib/volumes.py:501
#: nova/api/openstack/compute/plugins/v3/assisted_volume_snapshots.py:72
#, python-format
msgid "Delete snapshot with id: %s"
msgstr "Supprimer l'instantané avec l'ID : %s"

#: nova/api/openstack/compute/contrib/attach_interfaces.py:120
msgid "Attach interface"
msgstr "Connexion à l'interface"

#: nova/api/openstack/compute/contrib/attach_interfaces.py:154
#, python-format
msgid "Detach interface %s"
msgstr "Déconnexion de l'interface %s"

#: nova/api/openstack/compute/contrib/hosts.py:152
#: nova/api/openstack/compute/plugins/v3/hosts.py:134
#, python-format
msgid "Putting host %(host_name)s in maintenance mode %(mode)s."
msgstr "Placement de l'hôte %(host_name)s en mode maintenance %(mode)s."

#: nova/api/openstack/compute/contrib/hosts.py:175
#: nova/api/openstack/compute/plugins/v3/hosts.py:156
#, python-format
msgid "Enabling host %s."
msgstr "Activation de l'hôte %s."

#: nova/api/openstack/compute/contrib/hosts.py:177
#: nova/api/openstack/compute/plugins/v3/hosts.py:158
#, python-format
msgid "Disabling host %s."
msgstr "Désactivation de l'hôte %s."

#: nova/api/openstack/compute/contrib/server_external_events.py:97
#: nova/api/openstack/compute/plugins/v3/server_external_events.py:86
#, python-format
msgid "Creating event %(name)s:%(tag)s for instance %(instance_uuid)s"
msgstr ""
"Création de l'événement %(name)s : %(tag)s pour l'instance %(instance_uuid)s"

#: nova/api/openstack/compute/contrib/volumes.py:77
#, python-format
msgid "vol=%s"
msgstr "vol = %s"

#: nova/api/openstack/compute/contrib/volumes.py:111
#, python-format
msgid "Delete volume with id: %s"
msgstr "Supprimer le volume avec l'ID : %s"

#: nova/api/openstack/compute/contrib/volumes.py:295
#, python-format
msgid "Attach volume %(volume_id)s to instance %(server_id)s at %(device)s"
msgstr ""
"Connexion du volume %(volume_id)s à l'instance %(server_id)s à %(device)s"

#: nova/api/openstack/compute/contrib/volumes.py:539
#, python-format
msgid "Create snapshot from volume %s"
msgstr "Créer un instantané depuis le volume %s"

#: nova/cells/messaging.py:1136
#, python-format
msgid ""
"Forcing a sync of instances, project_id=%(projid_str)s, updated_since="
"%(since_str)s"
msgstr ""
"Synchronisation forcée des instances, project_id=%(projid_str)s, "
"updated_since=%(since_str)s"

#: nova/cells/scheduler.py:239
#, python-format
msgid ""
"No cells available when scheduling.  Will retry in %(sleep_time)s second(s)"
msgstr ""
"Aucune cellule disponible lors de la planification. Une nouvelle tentative "
"aura lieu dans %(sleep_time)s seconde(s)"

#: nova/cells/filters/target_cell.py:59
#, python-format
msgid ""
"Forcing direct route to %(cell_name)s because of 'target_cell' scheduler hint"
msgstr ""

#: nova/compute/api.py:1508
msgid "instance termination disabled"
msgstr "Arrêt de l'instance désactivé"

#: nova/compute/api.py:1521
#, python-format
msgid "Working on deleting snapshot %s from shelved instance..."
msgstr ""

#: nova/compute/api.py:1591
msgid "Instance is already in deleting state, ignoring this request"
msgstr "L'instance est déjà dans un état de suppression, ignoré cette requête"

#: nova/compute/api.py:1636
#, python-format
msgid ""
"Found an unconfirmed migration during delete, id: %(id)s, status: %(status)s"
msgstr ""

#: nova/compute/api.py:1646
msgid "Instance may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1663
#, python-format
msgid "Migration %s may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1719
msgid ""
"instance is in SHELVED_OFFLOADED state, cleanup the instance's info from "
"database."
msgstr ""

#: nova/compute/api.py:2218
#, python-format
msgid "Skipping quiescing instance: %(reason)s."
msgstr ""

#: nova/compute/api.py:3879
#, python-format
msgid "Create Security Group %s"
msgstr "Création du groupe de sécurité %s"

#: nova/compute/api.py:3984
#, python-format
msgid "Delete security group %s"
msgstr "Suppression du groupe de sécurité %s"

#: nova/compute/claims.py:167
msgid "Claim successful"
msgstr "Réclamation réussie"

#: nova/compute/claims.py:236
#, python-format
msgid "Total %(type)s: %(total)d %(unit)s, used: %(used).02f %(unit)s"
msgstr "Total %(type)s: %(total)d %(unit)s, utilisé: %(used).02f %(unit)s"

#: nova/compute/claims.py:243
#, python-format
msgid "%(type)s limit not specified, defaulting to unlimited"
msgstr "%(type)s limite non spécifiée, valeur par défaut 'non limité'"

#: nova/compute/claims.py:250
#, python-format
msgid "%(type)s limit: %(limit).02f %(unit)s, free: %(free).02f %(unit)s"
msgstr ""
"%(type)s limite: %(limit).02f %(unit)s, disponible: %(free).02f %(unit)s"

#: nova/compute/manager.py:301
#, python-format
msgid "Task possibly preempted: %s"
msgstr ""

#: nova/compute/manager.py:791
#, python-format
msgid ""
"Deleting instance as its host (%(instance_host)s) is not equal to our host "
"(%(our_host)s)."
msgstr ""
"Suppression de l'instance car son hôte (%(instance_host)s) ne correspond pas "
"notre hôte (%(our_host)s)."

#: nova/compute/manager.py:806
msgid ""
"Instance has been marked deleted already, removing it from the hypervisor."
msgstr ""
"L'instance a déjà été marquée comme supprimée, déréférencement de "
"l'hyperviseur."

#: nova/compute/manager.py:974
msgid ""
"Service started deleting the instance during the previous run, but did not "
"finish. Restarting the deletion now."
msgstr ""

#: nova/compute/manager.py:1099
msgid "Instance found in migrating state during startup. Resetting task_state"
msgstr ""
"Instance trouvée à l'état en cours de migration lors du démarrage. "
"Redéfinition de task_state"

#: nova/compute/manager.py:1121
msgid "Rebooting instance after nova-compute restart."
msgstr "Redémarrage de l'instance après redémarrage de nova-compute."

#: nova/compute/manager.py:1171
#, python-format
msgid "VM %(state)s (Lifecycle Event)"
msgstr ""

#: nova/compute/manager.py:1698 nova/compute/manager.py:2149
msgid "Starting instance..."
msgstr "Démarrage de l'instance..."

#: nova/compute/manager.py:2520
#, python-format
msgid "%(action_str)s instance"
msgstr "Instance %(action_str)s"

#: nova/compute/manager.py:2686
msgid "Instance disappeared during terminate"
msgstr ""

#: nova/compute/manager.py:2730
msgid "Instance is already powered off in the hypervisor when stop is called."
msgstr ""
"L'instance est déjà éteinte dans l'hyperviseur quand l'arrêt est appelé."

#: nova/compute/manager.py:2893
msgid "Rebuilding instance"
msgstr "Régénération de l'instance"

#: nova/compute/manager.py:2910
msgid "disk on shared storage, recreating using existing disk"
msgstr ""
"Disque sur la mémoire partagée ; recréation à l'aide du disque existant"

#: nova/compute/manager.py:2914
#, python-format
msgid "disk not on shared storage, rebuilding from: '%s'"
msgstr ""

#: nova/compute/manager.py:3000
#, python-format
msgid "bringing vm to original state: '%s'"
msgstr "Restauration de l'état original de la machine virtuelle : '%s'"

#: nova/compute/manager.py:3031
#, python-format
msgid "Detaching from volume api: %s"
msgstr "Déconnexion de l'API volume : %s"

#: nova/compute/manager.py:3058
msgid "Rebooting instance"
msgstr "Réamorçage de l'instance"

#: nova/compute/manager.py:3196
msgid "instance snapshotting"
msgstr "exécution d'instantané d'instance"

#: nova/compute/manager.py:3333
msgid "Root password set"
msgstr "Mot de passe root défini"

#: nova/compute/manager.py:3381
#, python-format
msgid "injecting file to %s"
msgstr ""

#: nova/compute/manager.py:3419
msgid "Rescuing"
msgstr "Mode secours"

#: nova/compute/manager.py:3468
msgid "Unrescuing"
msgstr "Sortie du mode secours"

#: nova/compute/manager.py:3546
#, python-format
msgid "Migration %s is already confirmed"
msgstr ""

#: nova/compute/manager.py:3567
msgid "Instance is not found during confirmation"
msgstr ""

#: nova/compute/manager.py:3755
#, python-format
msgid "Updating instance to original state: '%s'"
msgstr ""

#: nova/compute/manager.py:3802
msgid "Migrating"
msgstr "Migration"

#: nova/compute/manager.py:4145
msgid "Pausing"
msgstr "Mise en pause"

#: nova/compute/manager.py:4161
msgid "Unpausing"
msgstr "Sortie de pause"

#: nova/compute/manager.py:4199 nova/compute/manager.py:4216
msgid "Retrieving diagnostics"
msgstr "Extraction des diagnostics"

#: nova/compute/manager.py:4255
msgid "Resuming"
msgstr "Reprise en cours"

#: nova/compute/manager.py:4486
msgid "Get console output"
msgstr "Obtenir l'affichage de la console"

#: nova/compute/manager.py:4731
#, python-format
msgid "Attaching volume %(volume_id)s to %(mountpoint)s"
msgstr "Connexion du volume %(volume_id)s à %(mountpoint)s"

#: nova/compute/manager.py:4756
#, python-format
msgid "Detach volume %(volume_id)s from mountpoint %(mp)s"
msgstr "Déconnexion du volume %(volume_id)s du point de montage %(mp)s"

#: nova/compute/manager.py:5248
msgid "_post_live_migration() is started.."
msgstr "_post_live_migration() est démarré.."

#: nova/compute/manager.py:5329
#, python-format
msgid "Migrating instance to %s finished successfully."
msgstr ""

#: nova/compute/manager.py:5331
msgid ""
"You may see the error \"libvirt: QEMU error: Domain not found: no domain "
"with matching name.\" This error can be safely ignored."
msgstr ""
"Vous pouvez voir l'erreur \"libvirt : erreur QEMU : Domaine non trouvé : "
"aucun domaine avec un nom correspondant.\" Cette erreur peut être ignorée."

#: nova/compute/manager.py:5356
msgid "Post operation of migration started"
msgstr "Opération postérieure à la migration démarrée"

#: nova/compute/manager.py:5620
#, python-format
msgid ""
"Found %(migration_count)d unconfirmed migrations older than "
"%(confirm_window)d seconds"
msgstr ""
"Détection de %(migration_count)d migrations non confirmées antérieures à "
"%(confirm_window)d secondes"

#: nova/compute/manager.py:5635
#, python-format
msgid ""
"Automatically confirming migration %(migration_id)s for instance "
"%(instance_uuid)s"
msgstr ""
"Confirmation automatique de la migration %(migration_id)s pour l'instance "
"%(instance_uuid)s"

#: nova/compute/manager.py:5689
#, python-format
msgid "Error auto-confirming resize: %s. Will retry later."
msgstr ""

#: nova/compute/manager.py:5737
#, python-format
msgid ""
"Running instance usage audit for host %(host)s from %(begin_time)s to "
"%(end_time)s. %(number_instances)s instances."
msgstr ""
"Exécution de l'audit d'utilisation de l'instance pour l'hôte %(host)s de "
"%(begin_time)s à %(end_time)s. %(number_instances)s instances."

#: nova/compute/manager.py:5785
msgid "Updating bandwidth usage cache"
msgstr "Mise à jour du cache d'utilisation de la bande passante"

#: nova/compute/manager.py:5966 nova/compute/manager.py:6023
#, python-format
msgid ""
"During sync_power_state the instance has a pending task (%(task)s). Skip."
msgstr ""
"Durant sync_power_state l'instance à une tâche en attente (%(task)s). Passer."

#: nova/compute/manager.py:6010
#, python-format
msgid ""
"During the sync_power process the instance has moved from host %(src)s to "
"host %(dst)s"
msgstr ""
"Lors du processus sync_power, l'instance a été déplacée depuis l'hôte "
"%(src)s vers l'hôte %(dst)s"

#: nova/compute/manager.py:6031
#, python-format
msgid ""
"During _sync_instance_power_state the DB power_state (%(db_power_state)s) "
"does not match the vm_power_state from the hypervisor (%(vm_power_state)s). "
"Updating power_state in the DB to match the hypervisor."
msgstr ""

#: nova/compute/manager.py:6178
msgid "Reclaiming deleted instance"
msgstr "Récupération de l'instance supprimée"

#: nova/compute/manager.py:6208
#, python-format
msgid "Deleting orphan compute node %s"
msgstr ""

#: nova/compute/manager.py:6260
#, python-format
msgid ""
"Powering off instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6278
#, python-format
msgid ""
"Destroying instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6326
#, python-format
msgid "Setting instance back to %(state)s after: %(error)s"
msgstr ""

#: nova/compute/manager.py:6336
#, python-format
msgid "Setting instance back to ACTIVE after: %s"
msgstr "Rétablissement de l'instance en statut ACTIVE après: %s"

#: nova/compute/resource_tracker.py:341
#, python-format
msgid "Compute_service record created for %(host)s:%(node)s"
msgstr "Enregistrement Compute_service créé pour %(host)s:%(node)s"

#: nova/compute/resource_tracker.py:373
#, python-format
msgid "Auditing locally available compute resources for node %(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:380
msgid ""
"Virt driver does not support 'get_available_resource'. Compute tracking is "
"disabled."
msgstr ""

#: nova/compute/resource_tracker.py:477
#, python-format
msgid "Compute_service record updated for %(host)s:%(node)s"
msgstr "Enregistrement Compute_service mis à jour pour %(host)s:%(node)s"

#: nova/compute/resource_tracker.py:552
#, python-format
msgid "Total usable vcpus: %(tcpu)s, total allocated vcpus: %(ucpu)s"
msgstr ""

#: nova/compute/resource_tracker.py:559
#, python-format
msgid ""
"Final resource view: name=%(node)s phys_ram=%(phys_ram)sMB used_ram="
"%(used_ram)sMB phys_disk=%(phys_disk)sGB used_disk=%(used_disk)sGB "
"total_vcpus=%(total_vcpus)s used_vcpus=%(used_vcpus)s pci_stats=%(pci_stats)s"
msgstr ""

#: nova/compute/resource_tracker.py:641
#, python-format
msgid "Updating from migration %s"
msgstr "Mise à jour à partir de la migration %s"

#: nova/conductor/api.py:294
msgid "nova-conductor connection established successfully"
msgstr ""

#: nova/consoleauth/manager.py:98
#, python-format
msgid "Received Token: %(token)s, %(token_dict)s"
msgstr ""

#: nova/consoleauth/manager.py:123
#, python-format
msgid "Checking Token: %(token)s, %(token_valid)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:3422
#, python-format
msgid ""
"quota_usages out of sync, updating. project_id: %(project_id)s, user_id: "
"%(user_id)s, resource: %(res)s, tracked usage: %(tracked_use)s, actual "
"usage: %(in_use)s"
msgstr ""
"quota_usages de la synchronisation, la mise à jour. project_id : "
"%(project_id)s, user_id : %(user_id)s, ressource : %(res)s, suivi "
"d'utilisation : %(tracked_use)s, utilisation effective : %(in_use)s"

#: nova/db/sqlalchemy/api.py:5234
#, python-format
msgid ""
"Volume(%s) has lower stats then what is in the database. Instance must have "
"been rebooted or crashed. Updating totals."
msgstr ""
"Les statistiques du volume(%s) sont inférieures à celles de la base de "
"données. L'instance a dûe être redémarrée (volontairement ou plantage). "
"Synchronisation des données."

#: nova/db/sqlalchemy/migrate_repo/versions/234_add_expire_reservations_index.py:36
#: nova/db/sqlalchemy/migrate_repo/versions/248_add_expire_reservations_index.py:36
msgid ""
"Skipped adding reservations_deleted_expire_idx because an equivalent index "
"already exists."
msgstr ""
"Passé l'ajout de reservations_deleted_expire_idx car un index équivalent "
"existe déjà."

#: nova/db/sqlalchemy/migrate_repo/versions/234_add_expire_reservations_index.py:58
#: nova/db/sqlalchemy/migrate_repo/versions/248_add_expire_reservations_index.py:58
msgid ""
"Skipped removing reservations_deleted_expire_idx because index does not "
"exist."
msgstr ""
"Passé le retrait de reservations_deleted_expire_idx car l'index n'existe pas."

#: nova/db/sqlalchemy/migrate_repo/versions/274_update_instances_project_id_index.py:36
msgid ""
"Skipped adding instances_project_id_deleted_idx because an equivalent index "
"already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/274_update_instances_project_id_index.py:58
msgid ""
"Skipped adding instances_project_id_idx because an equivalent index already "
"exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/277_add_fixed_ip_updated_index.py:40
#, python-format
msgid "Skipped adding %s because an equivalent index already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/277_add_fixed_ip_updated_index.py:51
#, python-format
msgid "Skipped removing %s because no such index exists"
msgstr ""

#: nova/image/s3.py:385
#, python-format
msgid "Image %s was deleted underneath us"
msgstr ""

#: nova/image/download/file.py:163
#, python-format
msgid "Copied %(source_file)s using %(module_str)s"
msgstr ""

#: nova/network/api.py:225 nova/network/neutronv2/api.py:1103
#, python-format
msgid "re-assign floating IP %(address)s from instance %(instance_id)s"
msgstr ""
"ré-affectation de l'adresse IP flottante %(address)s depuis l'instance "
"%(instance_id)s"

#: nova/network/driver.py:42
#, python-format
msgid "Loading network driver '%s'"
msgstr "Chargement du pilote de réseau '%s'"

#: nova/network/floating_ips.py:176
#, python-format
msgid "Floating IP %s is not associated. Ignore."
msgstr ""

#: nova/network/floating_ips.py:549
#, python-format
msgid "Starting migration network for instance %s"
msgstr "Démarrage de la migration réseau pour instance %s"

#: nova/network/floating_ips.py:585
#, python-format
msgid "Finishing migration network for instance %s"
msgstr ""

#: nova/network/manager.py:335
#, python-format
msgid "Configured network %(network)s on host %(host)s"
msgstr ""

#: nova/network/manager.py:508
#, python-format
msgid "Allocated network: '%s' for instance"
msgstr ""

#: nova/network/manager.py:571
#, python-format
msgid "Network deallocated for instance (fixed ips: '%s')"
msgstr ""

#: nova/network/minidns.py:201
#, python-format
msgid "deleted %s"
msgstr "suppression de %s"

#: nova/network/neutronv2/api.py:1575
#, python-format
msgid ""
"Port %s from network info_cache is no longer associated with instance in "
"Neutron. Removing from network info_cache."
msgstr ""

#: nova/network/security_group/neutron_driver.py:449
#: nova/network/security_group/neutron_driver.py:504
#, python-format
msgid "Adding security group %(security_group_id)s to port %(port_id)s"
msgstr "Ajout du groupe de sécurité %(security_group_id)s au port %(port_id)s"

#: nova/openstack/common/eventlet_backdoor.py:146
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr "Eventlet backdoor en écoute sur le port %(port)s for process %(pid)d"

#: nova/openstack/common/periodic_task.py:120
#, python-format
msgid "Skipping periodic task %(task)s because its interval is negative"
msgstr "Tâche périodique %(task)s ignorée car son intervalle est négatif"

#: nova/openstack/common/periodic_task.py:125
#, python-format
msgid "Skipping periodic task %(task)s because it is disabled"
msgstr "Tâche périodique %(task)s car elle est désactivée"

#: nova/openstack/common/service.py:173
#, python-format
msgid "Caught %s, exiting"
msgstr "%s interceptée, sortie"

#: nova/openstack/common/service.py:235
msgid "Parent process has died unexpectedly, exiting"
msgstr "Processus parent arrêté de manière inattendue, sortie"

#: nova/openstack/common/service.py:266
#, python-format
msgid "Child caught %s, exiting"
msgstr "L'enfant a reçu %s, sortie"

#: nova/openstack/common/service.py:305
msgid "Forking too fast, sleeping"
msgstr "Bifurcation trop rapide, pause"

#: nova/openstack/common/service.py:324
#, python-format
msgid "Started child %d"
msgstr "Enfant démarré %d"

#: nova/openstack/common/service.py:334
#, python-format
msgid "Starting %d workers"
msgstr "Démarrage des travailleurs %d"

#: nova/openstack/common/service.py:351
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr "Enfant %(pid)d arrêté par le signal %(sig)d"

#: nova/openstack/common/service.py:355
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr "Processus fils %(pid)s terminé avec le status %(code)d"

#: nova/openstack/common/service.py:390
#, python-format
msgid "Caught %s, stopping children"
msgstr "%s interceptée, arrêt de l'enfant"

#: nova/openstack/common/service.py:405
msgid "Wait called after thread killed. Cleaning up."
msgstr "Pause demandée après suppression de thread. Nettoyage."

#: nova/openstack/common/service.py:421
#, python-format
msgid "Waiting on %d children to exit"
msgstr "En attente %d enfants pour sortie"

#: nova/scheduler/host_manager.py:563
#, python-format
msgid "Removing dead compute node %(host)s:%(node)s from scheduler"
msgstr ""
"Suppression du noeud de traitement mort %(host)s:%(node)s du planificateur"

#: nova/scheduler/host_manager.py:625
#, python-format
msgid ""
"Received an update from an unknown host '%s'. Re-created its InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:643
#, python-format
msgid ""
"Received a delete update from an unknown host '%s'. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:661
#, python-format
msgid ""
"The instance sync for host '%s' did not match. Re-created its InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:665
#, python-format
msgid "Successfully synced instances from host '%s'."
msgstr ""

#: nova/scheduler/host_manager.py:669
#, python-format
msgid ""
"Received a sync request from an unknown host '%s'. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/client/report.py:73
#, python-format
msgid "Compute_service record updated for %s"
msgstr "Enregistrement de Compute_service mis à jour pour %s"

#: nova/scheduler/filters/utils.py:65
#, python-format
msgid "%(num_values)d values found, of which the minimum value will be used."
msgstr ""
"%(num_values)d valeurs trouvées, et c'est la valeur minimale qui sera "
"utilisée."

#: nova/virt/block_device.py:222
#, python-format
msgid "preserve multipath_id %s"
msgstr "conserver multipath_id %s"

#: nova/virt/block_device.py:427
#, python-format
msgid "Booting with volume %(volume_id)s at %(mountpoint)s"
msgstr "Amorçage avec le volume %(volume_id)s à %(mountpoint)s"

#: nova/virt/driver.py:1385
#, python-format
msgid "Loading compute driver '%s'"
msgstr "Chargement du pilote de calcul '%s'"

#: nova/virt/firewall.py:173 nova/virt/libvirt/firewall.py:345
msgid "Attempted to unfilter instance which is not filtered"
msgstr ""
"Vous avez essayé d'annuler le filtre d'une instance qui n'est pas filtrée"

#: nova/virt/firewall.py:443
#, python-format
msgid "instance chain %s disappeared during refresh, skipping"
msgstr "chaîne d'instance %s disparaît durant le rafraîchissement, à passer"

#: nova/virt/disk/mount/api.py:121
msgid "Device allocation failed. Will retry in 2 seconds."
msgstr ""
"L'allocation d'unité a échoué. Une nouvelle tentative aura lieu dans 2 "
"secondes."

#: nova/virt/disk/mount/loop.py:34
#, python-format
msgid "Loop mount error: %s"
msgstr "Erreur d'installation en boucle : %s"

#: nova/virt/disk/mount/nbd.py:91 nova/virt/disk/mount/nbd.py:104
#, python-format
msgid "NBD mount error: %s"
msgstr "Erreur d'installation NBD : %s"

#: nova/virt/disk/vfs/api.py:67
msgid "Unable to import guestfs, falling back to VFSLocalFS"
msgstr ""

#: nova/virt/hyperv/basevolumeutils.py:75
msgid "The ISCSI initiator name can't be found. Choosing the default one"
msgstr ""
"Le nom d'initiateur ISCSI est introuvable. Le nom par défaut est sélectionné."

#: nova/virt/hyperv/vmops.py:260
msgid "Spawning new instance"
msgstr "Génération d'une nouvelle instance"

#: nova/virt/hyperv/vmops.py:378 nova/virt/vmwareapi/vmops.py:664
msgid "Using config drive for instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:392 nova/virt/libvirt/driver.py:2826
#, python-format
msgid "Creating config drive at %(path)s"
msgstr "Création de l'unité de config à %(path)s"

#: nova/virt/hyperv/vmops.py:442
msgid "Got request to destroy instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:494
msgid "Soft shutdown succeeded."
msgstr "Arrêt logiciel réussi."

#: nova/virt/ironic/driver.py:708
#, python-format
msgid ""
"Config drive for instance %(instance)s on baremetal node %(node)s created."
msgstr ""

#: nova/virt/libvirt/driver.py:522
#, python-format
msgid "Connection event '%(enabled)d' reason '%(reason)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:686
msgid "During wait destroy, instance disappeared."
msgstr "Lors de la destruction de l'attente, l'instance a disparu."

#: nova/virt/libvirt/driver.py:691
msgid "Instance destroyed successfully."
msgstr "Instance détruite avec succès."

#: nova/virt/libvirt/driver.py:701
msgid "Instance may be started again."
msgstr "L'instance peut être redémarrée."

#: nova/virt/libvirt/driver.py:711
msgid "Going to destroy instance again."
msgstr "Tentative de redestruction de l'instance."

#: nova/virt/libvirt/driver.py:1369
msgid "Beginning live snapshot process"
msgstr "Démarrage du processus d'instantané en temps réel"

#: nova/virt/libvirt/driver.py:1372
msgid "Beginning cold snapshot process"
msgstr "Démarrage du processus d'instantané à froid"

#: nova/virt/libvirt/driver.py:1402
msgid "Snapshot extracted, beginning image upload"
msgstr "Instantané extrait, démarrage du téléchargement d'image"

#: nova/virt/libvirt/driver.py:1414
msgid "Snapshot image upload complete"
msgstr "Téléchargement d'image instantanée terminé"

#: nova/virt/libvirt/driver.py:1982
msgid "Instance soft rebooted successfully."
msgstr "Instance redémarrée par logiciel avec succès."

#: nova/virt/libvirt/driver.py:2025
msgid "Instance shutdown successfully."
msgstr "L'instance s'est arrêtée avec succès."

#: nova/virt/libvirt/driver.py:2033
msgid "Instance may have been rebooted during soft reboot, so return now."
msgstr "L'instance a sans doute été redémarrée par logiciel ; retour en cours."

#: nova/virt/libvirt/driver.py:2111
msgid "Instance rebooted successfully."
msgstr "L'instance a redémarré avec succès."

#: nova/virt/libvirt/driver.py:2153
msgid "Instance already shutdown."
msgstr "Instance déjà arrêtée."

#: nova/virt/libvirt/driver.py:2168
#, python-format
msgid "Instance shutdown successfully after %d seconds."
msgstr "Arrêt de l'instance réussie après %d secondes."

#: nova/virt/libvirt/driver.py:2197
#, python-format
msgid "Instance failed to shutdown in %d seconds."
msgstr "Échec de l'arrêt de l'instance dans %d seconds. "

#: nova/virt/libvirt/driver.py:2366
msgid "Instance spawned successfully."
msgstr "Instance générée avec succès."

#: nova/virt/libvirt/driver.py:2382
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr "data: %(data)r, fpath: %(fpath)r"

#: nova/virt/libvirt/driver.py:2417
msgid ""
"Instance is configured with a file console, but the backing file is not "
"(yet?) present"
msgstr ""

#: nova/virt/libvirt/driver.py:2428 nova/virt/libvirt/driver.py:2455
#, python-format
msgid "Truncated console log returned, %d bytes ignored"
msgstr "Journal de console tronqué retourné, %d octets ignorés"

#: nova/virt/libvirt/driver.py:2690
msgid "Creating image"
msgstr "Création de l'image"

#: nova/virt/libvirt/driver.py:2817
msgid "Using config drive"
msgstr "Utilisation de l'unité de config"

#: nova/virt/libvirt/driver.py:3605
msgid "Configuring timezone for windows instance to localtime"
msgstr "Configurer le fuseau horaire pour l'instance windows en heure locale"

#: nova/virt/libvirt/driver.py:4831
#, python-format
msgid ""
"Getting block stats failed, device might have been detached. Instance="
"%(instance_name)s Disk=%(disk)s Code=%(errcode)s Error=%(e)s"
msgstr ""
"Echec lors de la récupération des statistiques, le périphérique est peut-"
"être détaché. Instance=%(instance_name)s Disk=%(disk)s Code=%(errcode)s "
"Erreur=%(e)s"

#: nova/virt/libvirt/driver.py:4837
#, python-format
msgid ""
"Could not find domain in libvirt for instance %s. Cannot get block stats for "
"device"
msgstr ""
"Domaine introuvable dans libvirt pour l'instance %s. Impossible d'obtenir "
"les stats de bloc pour l'unité"

#: nova/virt/libvirt/driver.py:5158
#, python-format
msgid "Instance launched has CPU info: %s"
msgstr "L'instance lancée a l'info CPU : %s"

#: nova/virt/libvirt/driver.py:5553
#, python-format
msgid "Error %(ex)s, migration failed"
msgstr ""

#: nova/virt/libvirt/driver.py:5594
#, python-format
msgid ""
"Migration running for %(secs)d secs, memory %(progress)d%% remaining; (bytes "
"processed=%(processed)d, remaining=%(remaining)d, total=%(total)d)"
msgstr ""

#: nova/virt/libvirt/driver.py:5612
msgid "Migration operation has completed"
msgstr ""

#: nova/virt/libvirt/driver.py:6307
msgid "Instance running successfully."
msgstr "L'instance s'exécute avec succès."

#: nova/virt/libvirt/driver.py:6662
#, python-format
msgid "Deleting instance files %s"
msgstr "Suppression des fichiers d'instance %s "

#: nova/virt/libvirt/driver.py:6675
#, python-format
msgid "Deletion of %s failed"
msgstr "La suppression de %s a échoué "

#: nova/virt/libvirt/driver.py:6679
#, python-format
msgid "Deletion of %s complete"
msgstr "Suppression de %s est complète"

#: nova/virt/libvirt/firewall.py:115
msgid "Called setup_basic_filtering in nwfilter"
msgstr "setup_basic_filtering appelé dans nwfilter"

#: nova/virt/libvirt/firewall.py:123
msgid "Ensuring static filters"
msgstr "Garantie des filtres statiques"

#: nova/virt/libvirt/host.py:686
#, python-format
msgid ""
"Unable to use bulk domain list APIs, falling back to slow code path: %(ex)s"
msgstr ""
"Incapable d'utiliser les liste API de domaines par bloc, on revient au "
"chemin : %(ex)s"

#: nova/virt/libvirt/host.py:736
#, python-format
msgid "Libvirt host capabilities %s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:398
#, python-format
msgid "Failed to get image info from path %(path)s; error: %(error)s"
msgstr ""
"Echec à obtenir les informations d'image du chemin %(path)s; erreur : "
"%(error)s"

#: nova/virt/libvirt/imagecache.py:191
#, python-format
msgid "Writing stored info to %s"
msgstr "Ecriture d'informations stockées dans %s"

#: nova/virt/libvirt/imagecache.py:414
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): image verification skipped, no hash stored"
msgstr ""
"image %(id)s à (%(base_file)s) : vérification d'image ignorée, aucun hachage "
"stocké"

#: nova/virt/libvirt/imagecache.py:423
#, python-format
msgid "%(id)s (%(base_file)s): generating checksum"
msgstr "%(id)s (%(base_file)s) : génération d'un total de contrôle"

#: nova/virt/libvirt/imagecache.py:452
#, python-format
msgid "Base or swap file too young to remove: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:455
#, python-format
msgid "Removing base or swap file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:505
#, python-format
msgid "image %(id)s at (%(base_file)s): checking"
msgstr "image %(id)s à (%(base_file)s) : vérification"

#: nova/virt/libvirt/imagecache.py:529
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): in use: on this node %(local)d local, "
"%(remote)d on other nodes sharing this instance storage"
msgstr ""
"image %(id)s à (%(base_file)s) : en cours d'utilisation : sur ce noeud "
"%(local)d local, %(remote)d sur d'autres noeuds partageant ce stockage "
"d'instance"

#: nova/virt/libvirt/imagecache.py:612
#, python-format
msgid "Active base files: %s"
msgstr "Fichiers de base actifs : %s"

#: nova/virt/libvirt/imagecache.py:615
#, python-format
msgid "Corrupt base files: %s"
msgstr "Fichiers de base endommagés : %s"

#: nova/virt/libvirt/imagecache.py:619
#, python-format
msgid "Removable base files: %s"
msgstr "Fichiers de base pouvant être retirés : %s"

#: nova/virt/libvirt/quobyte.py:50
#, python-format
msgid "Mounted volume: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:259
#, python-format
msgid "tap-ctl check: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:589
msgid "findmnt tool is not installed"
msgstr "L'outil findmnt n'est pas installé"

#: nova/virt/libvirt/volume.py:1555
#, python-format
msgid "Fixing previous mount %s which was not unmounted correctly."
msgstr ""

#: nova/virt/libvirt/volume.py:1576
#, python-format
msgid "Trying to disconnected unmounted volume at %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:450
#, python-format
msgid "Invalid cluster or resource pool name : %s"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:289
#, python-format
msgid "Moved virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:307
#, python-format
msgid "Copied virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:321
#, python-format
msgid "Deleted virtual disk %s."
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:162
#, python-format
msgid "Image %s is no longer used by this node. Pending deletion!"
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:167
#, python-format
msgid "Image %s is no longer used. Deleting!"
msgstr ""

#: nova/virt/vmwareapi/images.py:362
#, python-format
msgid "Downloaded image file data %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/images.py:365 nova/virt/vmwareapi/images.py:436
msgid "The imported VM was unregistered"
msgstr ""

#: nova/virt/vmwareapi/images.py:431
#, python-format
msgid "Downloaded OVA image file %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1308
msgid "Destroyed the VM"
msgstr "Machine virtuelle détruite"

#: nova/virt/vmwareapi/vmops.py:768
msgid "Created linked-clone VM from snapshot"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1308 nova/virt/xenapi/vmops.py:1677
#, python-format
msgid "Found %(instance_count)d hung reboots older than %(timeout)d seconds"
msgstr ""
"Arrêt détecté, %(instance_count)d redémarrée dans les %(timeout)d secondes"

#: nova/virt/vmwareapi/vmops.py:1312 nova/virt/xenapi/vmops.py:1681
msgid "Automatically hard rebooting"
msgstr "Réinitialisé automatiquement"

#: nova/virt/vmwareapi/volumeops.py:443
#, python-format
msgid ""
"The volume's backing has been relocated to %s. Need to consolidate backing "
"disk file."
msgstr ""

#: nova/virt/xenapi/agent.py:396
msgid ""
"XenServer tools installed in this image are capable of network injection.  "
"Networking files will not bemanipulated"
msgstr ""
"Les outils XenServer installés dans cette image peuvent effectuer une "
"injection réseau. Les fichiers réseau ne seront pas manipulés"

#: nova/virt/xenapi/agent.py:404
msgid ""
"XenServer tools are present in this image but are not capable of network "
"injection"
msgstr ""
"Des outils XenServer sont présents dans cette image mais ils ne peuvent pas "
"effectuer une injection réseau "

#: nova/virt/xenapi/agent.py:408
msgid "XenServer tools are not installed in this image"
msgstr "Les outils XenServer ne sont pas installés dans cette image"

#: nova/virt/xenapi/host.py:75
#, python-format
msgid ""
"Instance %(name)s running on %(host)s could not be found in the database: "
"assuming it is a worker VM and skip ping migration to a new host"
msgstr ""
"L'instance %(name)s en cours d'exécution sur %(host)s est introuvable dans "
"la base de données : on suppose qu'il s'agit d'une machine virtuelle de "
"travailleur et le ping de migration pour un nouvel hôte est ignoré"

#: nova/virt/xenapi/vm_utils.py:395
#, python-format
msgid "VBD %s already detached"
msgstr "VBD %s déjà déconnecté"

#: nova/virt/xenapi/vm_utils.py:398
#, python-format
msgid ""
"VBD %(vbd_ref)s uplug failed with \"%(err)s\", attempt %(num_attempt)d/"
"%(max_attempts)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:685
#, python-format
msgid "Deleted %s snapshots."
msgstr "Snapshots %s supprimés."

#: nova/virt/xenapi/vm_utils.py:1328
#, python-format
msgid ""
"Image creation data, cacheable: %(cache)s, downloaded: %(downloaded)s "
"duration: %(duration).2f secs for image %(image_id)s"
msgstr ""
"Données de création de l'image, capacité du cache : %(cache)s, téléchargé : "
"%(downloaded)s durée : %(duration).2f secondes pour l'image %(image_id)s"

#: nova/virt/xenapi/vm_utils.py:2176
#, python-format
msgid "Disconnecting stale VDI %s from compute domU"
msgstr "Déconnexion VDI périmé %s à partir de l'ordinateur domU"

#: nova/virt/xenapi/vm_utils.py:2469
msgid "Manipulating interface files directly"
msgstr "Manipulation directe des fichiers d'interfaces"

#: nova/virt/xenapi/vm_utils.py:2478
#, python-format
msgid "Failed to mount filesystem (expected for non-linux instances): %s"
msgstr ""
"Echec du montage du système de fichiers (attendu pour les instances non "
"Linux) : %s"

#: nova/virt/xenapi/vmops.py:1263
msgid "Starting halted instance found during reboot"
msgstr "Démarrage de l'instance interrompue détectée durant le redémarrage"

#: nova/virt/xenapi/vmops.py:1467
msgid "Destroying VM"
msgstr "Destruction de la machine virtuelle"

#: nova/virt/xenapi/volumeops.py:64
#, python-format
msgid "Connected volume (vdi_uuid): %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:127
#, python-format
msgid "Dev %(dev_number)s attached to instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:149
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr ""
"Le point de montage %(mountpoint)s à été détaché de l'instance "
"%(instance_name)s"

#: nova/vnc/xvp_proxy.py:94
#, python-format
msgid "Error in handshake format: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:100
#, python-format
msgid "Error in handshake: %s"
msgstr "Erreur dans l'établissement de liaison : %s"

#: nova/vnc/xvp_proxy.py:115
#, python-format
msgid "Invalid request: %s"
msgstr "Demande non valide : %s"

#: nova/vnc/xvp_proxy.py:135
#, python-format
msgid "Request: %s"
msgstr "Demande : %s"

#: nova/vnc/xvp_proxy.py:138
#, python-format
msgid "Request made with missing token: %s"
msgstr "Demande effectuée avec un jeton manquant : %s"

#: nova/vnc/xvp_proxy.py:148
#, python-format
msgid "Request made with invalid token: %s"
msgstr "Demande effectuée avec un jeton non valide : %s"

#: nova/vnc/xvp_proxy.py:155
#, python-format
msgid "Unexpected error: %s"
msgstr "Erreur inattendue : %s"

#: nova/vnc/xvp_proxy.py:175
#, python-format
msgid "Starting nova-xvpvncproxy node (version %s)"
msgstr "Démarrage du noeud nova-xvpvncproxy (version %s)"

#: nova/volume/encryptors/luks.py:110
#, python-format
msgid "%s is not a valid LUKS device; formatting device for first use"
msgstr ""
